In [184]:
import pandas as pd

In [185]:
import os

In [186]:
source = os.getcwd() # dataset root dir
a_paths = [] # list of paths to activities 'a'
for i in range(1,20):
    fname = 'a' + str(0) + str(i) if i<10 else 'a' + str(i)
    a_paths.append(os.path.join(source, fname))
print('a_paths contains:\n\t{}'.format(a_paths))

a_paths contains:
	['/Users/fahad/Desktop/Tariq/data/a01', '/Users/fahad/Desktop/Tariq/data/a02', '/Users/fahad/Desktop/Tariq/data/a03', '/Users/fahad/Desktop/Tariq/data/a04', '/Users/fahad/Desktop/Tariq/data/a05', '/Users/fahad/Desktop/Tariq/data/a06', '/Users/fahad/Desktop/Tariq/data/a07', '/Users/fahad/Desktop/Tariq/data/a08', '/Users/fahad/Desktop/Tariq/data/a09', '/Users/fahad/Desktop/Tariq/data/a10', '/Users/fahad/Desktop/Tariq/data/a11', '/Users/fahad/Desktop/Tariq/data/a12', '/Users/fahad/Desktop/Tariq/data/a13', '/Users/fahad/Desktop/Tariq/data/a14', '/Users/fahad/Desktop/Tariq/data/a15', '/Users/fahad/Desktop/Tariq/data/a16', '/Users/fahad/Desktop/Tariq/data/a17', '/Users/fahad/Desktop/Tariq/data/a18', '/Users/fahad/Desktop/Tariq/data/a19']

In [187]:
p_fnames = [] # list of p files name [p1..p8]
for i in range(1,9):
    p_fnames.append('p'+str(i))
print('p_fnames contains:\n\t{}'.format(p_fnames))

p_fnames contains:
	['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8']

In [188]:
s_fnames = [] # list of s files name [s01..s60]
for i in range(1, 61): 
    n = 's' + str(0) + str(i) + '.txt' if i < 10 else 's' + str(i) + '.txt'
    s_fnames.append(n)
print('s_fnames size is {}'.format(len(s_fnames)))
print(s_fnames[0])

s_fnames size is 60
s01.txt

* **a_paths** contains paths to each Activity 

* **p_fnames** contains names of Subject folders 

* **s_fnames** contains names of Segments folders

In [189]:
headers = []
units = ['T', 'RA', 'LA', 'RL', 'LL']
dims = ['x', 'y', 'z']
sensors = ['acc', 'gyro', 'mag']
for unit in units:
    for sensor in sensors:
        for dim in dims:
            s = unit + '_' + dim + sensor
            headers.append(s)
print(headers)

['T_xacc', 'T_yacc', 'T_zacc', 'T_xgyro', 'T_ygyro', 'T_zgyro', 'T_xmag', 'T_ymag', 'T_zmag', 'RA_xacc', 'RA_yacc', 'RA_zacc', 'RA_xgyro', 'RA_ygyro', 'RA_zgyro', 'RA_xmag', 'RA_ymag', 'RA_zmag', 'LA_xacc', 'LA_yacc', 'LA_zacc', 'LA_xgyro', 'LA_ygyro', 'LA_zgyro', 'LA_xmag', 'LA_ymag', 'LA_zmag', 'RL_xacc', 'RL_yacc', 'RL_zacc', 'RL_xgyro', 'RL_ygyro', 'RL_zgyro', 'RL_xmag', 'RL_ymag', 'RL_zmag', 'LL_xacc', 'LL_yacc', 'LL_zacc', 'LL_xgyro', 'LL_ygyro', 'LL_zgyro', 'LL_xmag', 'LL_ymag', 'LL_zmag']

In [190]:
a_dfs = [] # list of activities df
p_dfs = [] # list of temp subject df
s_dfs = [] # list of temp segments df

for a in a_paths:
    for p in p_fnames:
        ppath = os.path.join(a, p) # construct a path to p
        for s in s_fnames: # read and prepare the segment files in p
            spath = os.path.join(ppath, s) # construct a path to a
            df = pd.read_csv(spath, delimiter=',', names=headers)
            df.insert(0, 'Segment', s[:3]) # add Segment column with s## as a value
            s_dfs.append(df)
        
        df = pd.concat(s_dfs) # merge all Segments that belongs to a Subject
        df.insert(0, 'Subject', p)
        p_dfs.append(df) # append to p_dfs
        s_dfs.clear() # empty s_dfs 
        
    df = pd.concat(p_dfs) # merge all Subjects that belongs to the an Activity
    df.insert(0, 'Activity', a[len(a)-3:len(a)])
    a_dfs.append(df) # append to p_dfs
    p_dfs.clear() # empty p_dfs 
len(a_dfs)

19

In [191]:
dataset = pd.concat(a_dfs) # merge all activities data

In [192]:
dataset.shape # show dim of the table

(1140000, 48)

In [193]:
dataset.head(5) # show the first 5 rows

,Activity,Subject,Segment,T_xacc,T_yacc,T_zacc,T_xgyro,T_ygyro,T_zgyro,T_xmag,...,RL_zmag,LL_xacc,LL_yacc,LL_zacc,LL_xgyro,LL_ygyro,LL_zgyro,LL_xmag,LL_ymag,LL_zmag
0,a01,p1,s01,8.1305,1.0349,5.4217,-0.009461,0.001915,-0.003424,-0.78712,...,-0.036453,-2.8071,-9.0812,2.6220,-0.000232,-0.012092,-0.004457,0.74017,0.30053,-0.057730
1,a01,p1,s01,8.1305,1.0202,5.3843,-0.009368,0.023485,0.001953,-0.78717,...,-0.034005,-2.8146,-9.0737,2.6218,-0.014784,-0.016477,0.002789,0.73937,0.30183,-0.057514
2,a01,p1,s01,8.1604,1.0201,5.3622,0.015046,0.014330,0.000204,-0.78664,...,-0.036489,-2.8221,-9.0886,2.6366,-0.012770,0.005717,-0.007918,0.73955,0.30052,-0.057219
3,a01,p1,s01,8.1603,1.0052,5.3770,0.006892,0.018045,0.005649,-0.78529,...,-0.036151,-2.8071,-9.0811,2.6070,-0.005725,0.009620,0.006555,0.74029,0.30184,-0.057750
4,a01,p1,s01,8.1605,1.0275,5.3473,0.008811,0.030433,-0.005346,-0.78742,...,-0.033807,-2.8146,-9.0737,2.6218,-0.003929,-0.008371,0.002816,0.73845,0.30090,-0.057527

In [194]:
dataset.tail(5) # show the last 5 rows

,Activity,Subject,Segment,T_xacc,T_yacc,T_zacc,T_xgyro,T_ygyro,T_zgyro,T_xmag,...,RL_zmag,LL_xacc,LL_yacc,LL_zacc,LL_xgyro,LL_ygyro,LL_zgyro,LL_xmag,LL_ymag,LL_zmag
120,a19,p8,s60,16.00800,-2.01660,-0.58220,2.0271,1.65680,0.584410,-0.73195,...,-0.079139,-10.7520,4.3231,-4.5931,-0.23060,0.18089,-2.08230,0.56876,0.39409,0.51817
121,a19,p8,s60,8.28230,-0.69936,0.48698,2.8879,1.60390,-0.020417,-0.73055,...,-0.030868,-5.1838,1.2551,-4.1113,1.81720,0.31251,-1.02160,0.53822,0.43745,0.50401
122,a19,p8,s60,2.71210,0.49967,0.84053,1.9964,1.46580,-0.072605,-0.72533,...,-0.063032,-1.0348,15.6940,1.2942,1.84210,0.34940,-0.28208,0.51752,0.47280,0.48925
123,a19,p8,s60,2.03080,-0.71349,-0.11264,1.7661,1.01030,-0.102120,-0.71933,...,-0.194960,-3.6479,-7.4632,-12.3640,-0.15026,1.56340,-0.36845,0.50440,0.51029,0.44648
124,a19,p8,s60,-0.04915,0.76302,-0.19343,2.5902,0.17909,0.011850,-0.71592,...,-0.212350,3.6284,15.0540,7.0935,-3.67780,0.15115,-0.74035,0.47028,0.43618,0.54511

In [195]:
# write the whole dataset to csv file 
dest = os.path.join(source,'dataset_out.csv')
dataset.to_csv(path_or_buf=dest, index=None, header=True)